export type DomainEventType =
  // Financeiro
  | 'FINANCE_TRANSFER_CREATED'
  | 'FINANCE_TRANSFER_APPROVED'
  | 'FINANCE_TRANSFER_REJECTED'
  | 'FINANCE_PAYOUT_SCHEDULED'
  | 'FINANCE_PAYOUT_FAILED'
  | 'FINANCE_CONCILIATION_DIVERGENCE'
  // Eventos & Operações (Fase 1.2)
  | 'EVENT_CREATED'
  | 'EVENT_UPDATED'
  | 'EVENT_DRAFT_CREATED'
  | 'EVENT_DRAFT_DISCARDED'
  | 'EVENT_INFORMATION_UPDATED'
  | 'EVENT_LOCATION_UPDATED'
  | 'EVENT_DATES_UPDATED'
  | 'EVENT_MEDIA_UPDATED'
  | 'EVENT_SETTINGS_UPDATED'
  | 'EVENT_RESPONSIBILITIES_UPDATED'
  | 'EVENT_WIZARD_STEP_CHANGED'
  | 'EVENT_CONTEXT_SELECTED'
  | 'EVENT_PUBLISHED'
  | 'EVENT_SALES_PAUSED'
  | 'EVENT_SALES_RESUMED'
  | 'EVENT_CANCELLED'
  | 'EVENT_FINISHED'
  | 'EVENT_ARCHIVED'
  | 'EVENT_BATCH_NEAR_EXHAUSTION'
  | 'EVENT_CAPACITY_LIMIT_APPROACHING'
  | 'EVENT_CHECKIN_STARTED'
  | 'EVENT_CHECKIN_PEAK'

  // Locais & Estrutura Física (Fase 1.2.3)
  | 'VENUE_CREATED'
  | 'VENUE_UPDATED'
  | 'VENUE_ARCHIVED'
  | 'VENUE_SECTION_CREATED'
  | 'VENUE_SECTION_UPDATED'
  | 'VENUE_SECTION_DELETED'
  | 'VENUE_MAP_CREATED'
  | 'VENUE_MAP_UPDATED'
  | 'VENUE_MAP_VERSION_CREATED'
  | 'VENUE_MAP_VERSION_ACTIVATED'
  | 'EVENT_VENUE_SELECTED'
  | 'EVENT_VENUE_CHANGED'
  | 'EVENT_SECTION_CONFIGURED'

  // Sessões & Capacidade Operacional (Fase 1.2.4)
  | 'EVENT_SESSION_CREATED'
  | 'EVENT_SESSION_UPDATED'
  | 'EVENT_SESSION_DUPLICATED'
  | 'EVENT_SESSION_CANCELLED'
  | 'EVENT_SESSION_STATUS_CHANGED'
  | 'SESSION_CAPACITY_UPDATED'
  | 'SESSION_SECTION_UPDATED'
  | 'SESSION_RESERVATION_CREATED'
  | 'SESSION_RESERVATION_DELETED'
  | 'SESSION_RECURRENCE_CREATED'

  // Atendimento SAC & Estorno
  | 'SAC_TICKET_CREATED'
  | 'SAC_SLA_WARNING'
  | 'SAC_SLA_BREACHED'
  | 'REFUND_REQUESTED'
  | 'REFUND_APPROVED'
  | 'CHARGEBACK_RECEIVED'
  // Comercial
  | 'COMMERCIAL_GOAL_REACHED'
  | 'COMMERCIAL_NEW_PRODUCER'
  // Suporte de Campo
  | 'SUPPORT_INCIDENT_OPENED'
  | 'SUPPORT_INCIDENT_CRITICAL'
  // Marketing & Remarketing
  | 'MARKETING_CAMPAIGN_BUDGET_REACHED'
  | 'MARKETING_PIXEL_FAILED'
  | 'REMARKETING_CART_ABANDONED'
  // Segurança
  | 'SECURITY_BRUTE_FORCE'
  | 'SECURITY_CONTEXT_TAMPERING'
  | 'SECURITY_STEP_UP_REAUTH'
  | 'SECURITY_UNAUTHORIZED_ACCESS'
  // Vendas & Pedidos
  | 'ORDER_PAID'
  // Documentos & Anexos (Fase 1.1.5.8)
  | 'DOCUMENT_UPLOADED'
  | 'DOCUMENT_EXPIRING'
  | 'DOCUMENT_QUARANTINED'
  | 'DOCUMENT_DELETED'
  // Tarefas & Workflow Engine (Fase 1.1.5.9)
  | 'TASK_CREATED'
  | 'TASK_ASSIGNED'
  | 'TASK_CLAIMED'
  | 'TASK_UPDATED'
  | 'TASK_COMMENT_CREATED'
  | 'TASK_SLA_WARNING'
  | 'TASK_ESCALATED'
  | 'TASK_COMPLETED'
  | 'TASK_CANCELLED'
  | 'TASK_REOPENED'
  // Operational Triggers for Workflows
  | 'RECONCILIATION_DIVERGENCE_DETECTED'
  | 'CHECKIN_FAILURE_RATE_HIGH'
  | 'TRACKING_HEALTH_FAILED'
  | 'ACCOUNTING_DIVERGENCE'
  // Configurações & Políticas (Fase 1.1.5.11)
  | 'CONFIGURATION_UPDATED'
  | 'CONFIGURATION_OVERRIDE_CREATED'
  | 'CONFIGURATION_OVERRIDE_REMOVED'
  | 'POLICY_CREATED'
  | 'POLICY_ACTIVATED'
  | 'POLICY_SCHEDULED'
  | 'POLICY_SUPERSEDED'
  | 'POLICY_ROLLED_BACK'
  | 'POLICY_CONFLICT_DETECTED'
  | 'FEATURE_FLAG_UPDATED'
  | 'KILL_SWITCH_TRIGGERED'
  | 'KILL_SWITCH_RESET'
  // Jobs & Processamentos Assíncronos (Fase 1.1.5.14)
  | 'JOB_CREATED'
  | 'JOB_QUEUED'
  | 'JOB_STARTED'
  | 'JOB_PROGRESS_UPDATED'
  | 'JOB_COMPLETED'
  | 'JOB_FAILED'
  | 'JOB_RETRYING'
  | 'JOB_CANCELLED'
  | 'JOB_DEAD_LETTER'
  | 'JOB_BATCH_COMPLETED'
  | 'JOB_BATCH_PARTIALLY_COMPLETED'
  | 'JOB_BATCH_FAILED'
  // Importação, Migração e Qualidade de Dados (Fase 1.1.5.15)
  | 'DATA_IMPORT_CREATED'
  | 'DATA_IMPORT_VALIDATED'
  | 'DATA_IMPORT_CONFIRMED'
  | 'DATA_IMPORT_STARTED'
  | 'DATA_IMPORT_PROGRESS'
  | 'DATA_IMPORT_COMPLETED'
  | 'DATA_IMPORT_FAILED'
  | 'DATA_IMPORT_CANCELLED'
  | 'DATA_IMPORT_ROLLED_BACK'
  | 'DATA_QUALITY_ISSUE_DETECTED'
  | 'DATA_MERGE_EXECUTED'
  | 'DATA_MIGRATION_COMPLETED';

export interface DomainEvent<T = any> {
  id: string; // Unique event ID for Idempotency
  type: DomainEventType;
  producerId?: string;
  eventId?: string;
  resourceType: string;
  resourceId: string;
  actorUserId?: string;
  data: T;
  metadata?: Record<string, any>;
  timestamp: Date;
}

export type DomainEventHandler = (event: DomainEvent) => Promise<void> | void;
